### ISSUE TITLE
[enhancement] sword swinging sounds

### ISSUE THREAD

**Issue by ghost** [PraxTube/insta-kill#1]
Could you please add an attack sound?

**Comment by PraxTube** [comment]
It's pretty easy to add and I actually meant to add some, but I couldn't find any that sound good (and I can't make my own). You got any?

**Comment by ghost** [comment]
https://freesound.org/people/Eponn/sounds/547040/
https://freesound.org/people/spycrah/sounds/471097/
https://freesound.org/people/SamsterBirdies/sounds/353708/
https://freesound.org/people/Artninja/sounds/700220/
https://freesound.org/people/crawfordjohnb@bellsouth.net/sounds/403235/

All of these sounds need some processing, but they sound good.

upd: [swing.zip](https://github.com/PraxTube/insta-kill/files/14164379/swing.zip)

**Comment by PraxTube** [comment]
I added the swing sound with a slight random pitch shift. I think it's okay, though it perhaps needs a bit work. I think it's a bit weird that the sound is the same for every swing, perhaps it should be different when the player hits an enemy, reflects a projectile or just hits nothing. The sound is [in this location](https://github.com/PraxTube/insta-kill/blob/add-strike-sound/assets/sounds/strike_sound.ogg).
